const SQUADS = {
  'Mexiko': [
    {name:'Guillermo Ochoa',pos:'GK',club:'AEL Limassol'},
    {name:'Raúl Rangel',pos:'GK',club:'Guadalajara'},
    {name:'Carlos Acevedo',pos:'GK',club:'Santos Laguna'},
    {name:'Jesús Gallardo',pos:'DEF',club:'Toluca'},
    {name:'César Montes',pos:'DEF',club:'Lokomotiv Moskau'},
    {name:'Jorge Sánchez',pos:'DEF',club:'PAOK'},
    {name:'Johan Vásquez',pos:'DEF',club:'Genoa'},
    {name:'Israel Reyes',pos:'DEF',club:'América'},
    {name:'Jesús Alberto Angulo',pos:'DEF',club:'UANL'},
    {name:'Julián Araujo',pos:'DEF',club:'Celtic'},
    {name:'Bryan González',pos:'DEF',club:'Guadalajara'},
    {name:'Edson Álvarez',pos:'MID',club:'Fenerbahçe'},
    {name:'Orbelín Pineda',pos:'MID',club:'AEK Athen'},
    {name:'Carlos Rodríguez',pos:'MID',club:'Cruz Azul'},
    {name:'Roberto Alvarado',pos:'MID',club:'Guadalajara'},
    {name:'Luis Romo',pos:'MID',club:'Guadalajara'},
    {name:'Luis Chávez',pos:'MID',club:'Dynamo Moskau'},
    {name:'Érick Sánchez',pos:'MID',club:'América'},
    {name:'Diego Lainez',pos:'MID',club:'UANL'},
    {name:'Raúl Jiménez',pos:'FWD',club:'Fulham'},
    {name:'Alexis Vega',pos:'FWD',club:'Toluca'},
    {name:'Santiago Giménez',pos:'FWD',club:'Milan'},
    {name:'César Huerta',pos:'FWD',club:'Anderlecht'},
    {name:'Julián Quiñones',pos:'FWD',club:'Al-Qadsiah'},
    {name:'Henry Martín',pos:'FWD',club:'América'},
    {name:'Rodrigo Aguirre',pos:'FWD',club:'UANL'}
  ],
  'Südafrika': [
    {name:'Ronwen Williams',pos:'GK',club:'Mamelodi Sundowns'},
    {name:'Ricardo Goss',pos:'GK',club:'Siwelele'},
    {name:'Sipho Chaine',pos:'GK',club:'Orlando Pirates'},
    {name:'Aubrey Modiba',pos:'DEF',club:'Mamelodi Sundowns'},
    {name:'Khuliso Mudau',pos:'DEF',club:'Mamelodi Sundowns'},
    {name:'Nkosinathi Sibisi',pos:'DEF',club:'Orlando Pirates'},
    {name:'Mbekezeli Mbokazi',pos:'DEF',club:'Chicago Fire'},
    {name:'Ime Okon',pos:'DEF',club:'Hannover 96'},
    {name:'Samukele Kabini',pos:'DEF',club:'Molde'},
    {name:'Khulumani Ndamane',pos:'DEF',club:'Mamelodi Sundowns'},
    {name:'Teboho Mokoena',pos:'MID',club:'Mamelodi Sundowns'},
    {name:'Sphephelo Sithole',pos:'MID',club:'Tondela'},
    {name:'Thalente Mbatha',pos:'MID',club:'Orlando Pirates'},
    {name:'Jayden Adams',pos:'MID',club:'Mamelodi Sundowns'},
    {name:'Themba Zwane',pos:'FWD',club:'Mamelodi Sundowns'},
    {name:'Lyle Foster',pos:'FWD',club:'Burnley'},
    {name:'Evidence Makgopa',pos:'FWD',club:'Orlando Pirates'},
    {name:'Oswin Appollis',pos:'FWD',club:'Orlando Pirates'},
    {name:'Iqraam Rayners',pos:'FWD',club:'Mamelodi Sundowns'}
  ],
  'Südkorea': [
    {name:'Kim Seung-gyu',pos:'GK',club:'FC Tokyo'},
    {name:'Jo Hyeon-woo',pos:'GK',club:'Ulsan HD'},
    {name:'Song Bum-keun',pos:'GK',club:'Jeonbuk Motors'},
    {name:'Kim Min-jae',pos:'DEF',club:'Bayern München'},
    {name:'Kim Moon-hwan',pos:'DEF',club:'Daejeon'},
    {name:'Seol Young-woo',pos:'DEF',club:'Roter Stern Belgrad'},
    {name:'Cho Yu-min',pos:'DEF',club:'Sharjah'},
    {name:'Lee Tae-seok',pos:'DEF',club:'Austria Wien'},
    {name:'Jens Castrop',pos:'DEF',club:'Mönchengladbach'},
    {name:'Lee Jae-sung',pos:'MID',club:'Mainz 05'},
    {name:'Hwang Hee-chan',pos:'MID',club:'Wolverhampton'},
    {name:'Hwang In-beom',pos:'MID',club:'Feyenoord'},
    {name:'Lee Kang-in',pos:'MID',club:'Paris Saint-Germain'},
    {name:'Paik Seung-ho',pos:'MID',club:'Birmingham City'},
    {name:'Bae Jun-ho',pos:'MID',club:'Stoke City'},
    {name:'Eom Ji-sung',pos:'MID',club:'Swansea City'},
    {name:'Yang Hyun-jun',pos:'MID',club:'Celtic'},
    {name:'Son Heung-min',pos:'FWD',club:'Los Angeles FC'},
    {name:'Cho Gue-sung',pos:'FWD',club:'Midtjylland'},
    {name:'Oh Hyeon-gyu',pos:'FWD',club:'Beşiktaş'}
  ],
  'Tschechien': [
    {name:'Matěj Kovář',pos:'GK',club:'PSV Eindhoven'},
    {name:'Jindřich Staněk',pos:'GK',club:'Slavia Prag'},
    {name:'Lukáš Horníček',pos:'GK',club:'Braga'},
    {name:'Vladimír Coufal',pos:'DEF',club:'TSG Hoffenheim'},
    {name:'Tomáš Holeš',pos:'DEF',club:'Slavia Prag'},
    {name:'Ladislav Krejčí',pos:'DEF',club:'Wolverhampton'},
    {name:'David Zima',pos:'DEF',club:'Slavia Prag'},
    {name:'Jaroslav Zelený',pos:'DEF',club:'Sparta Prag'},
    {name:'David Jurásek',pos:'DEF',club:'Slavia Prag'},
    {name:'David Douděra',pos:'DEF',club:'Slavia Prag'},
    {name:'Robin Hranáč',pos:'DEF',club:'TSG Hoffenheim'},
    {name:'Tomáš Souček',pos:'MID',club:'West Ham Utd'},
    {name:'Vladimír Darida',pos:'MID',club:'Hradec Králové'},
    {name:'Lukáš Provod',pos:'MID',club:'Slavia Prag'},
    {name:'Michal Sadílek',pos:'MID',club:'Slavia Prag'},
    {name:'Pavel Šulc',pos:'MID',club:'Lyon'},
    {name:'Lukáš Červ',pos:'MID',club:'Viktoria Plzeň'},
    {name:'Patrik Schick',pos:'FWD',club:'Bayer Leverkusen'},
    {name:'Adam Hložek',pos:'FWD',club:'TSG Hoffenheim'},
    {name:'Jan Kuchta',pos:'FWD',club:'Sparta Prag'},
    {name:'Tomáš Chorý',pos:'FWD',club:'Slavia Prag'},
    {name:'Mojmír Chytil',pos:'FWD',club:'Slavia Prag'}
  ],
  'Bosnien-Herzegowina': [
    {name:'Nikola Vasilj',pos:'GK',club:'FC St. Pauli'},
    {name:'Martin Zlomislić',pos:'GK',club:'Rijeka'},
    {name:'Osman Hadžikić',pos:'GK',club:'Slaven Belupo'},
    {name:'Edin Džeko',pos:'FWD',club:'Schalke 04'},
    {name:'Ermedin Demirović',pos:'FWD',club:'Augsburg'},
    {name:'Armin Gigović',pos:'MID',club:'Young Boys'},
    {name:'Dženis Burnić',pos:'MID',club:'Karlsruher SC'},
    {name:'Ivan Bašić',pos:'MID',club:'Astana'},
    {name:'Esmir Bajraktarević',pos:'MID',club:'PSV Eindhoven'},
    {name:'Amar Memić',pos:'MID',club:'Viktoria Plzeň'},
    {name:'Kerim Alajbegović',pos:'MID',club:'Red Bull Salzburg'},
    {name:'Sead Kolašinac',pos:'DEF',club:'Atalanta'},
    {name:'Anel Ahmedhodžić',pos:'DEF',club:'Sheffield Utd'},
    {name:'Dario Saric',pos:'DEF',club:'Sevilla'},
    {name:'Dženan Pejčinović',pos:'DEF',club:'Čukarički'},
    {name:'Danijel Subašić',pos:'DEF',club:'Monaco'},
    {name:'Josip Dropulić',pos:'DEF',club:'Dinamo Zagreb'}
  ],
  'Kanada': [
    {name:'Dayne St. Clair',pos:'GK',club:'Inter Miami'},
    {name:'Maxime Crépeau',pos:'GK',club:'Orlando City'},
    {name:'Owen Goodman',pos:'GK',club:'Barnsley'},
    {name:'Alphonso Davies',pos:'DEF',club:'Bayern München'},
    {name:'Alistair Johnston',pos:'DEF',club:'Celtic'},
    {name:'Joel Waterman',pos:'DEF',club:'Chicago Fire'},
    {name:'Derek Cornelius',pos:'DEF',club:'Rangers'},
    {name:'Moïse Bombito',pos:'DEF',club:'Nice'},
    {name:'Richie Laryea',pos:'DEF',club:'Toronto FC'},
    {name:'Niko Sigur',pos:'DEF',club:'Hajduk Split'},
    {name:'Luc de Fougerolles',pos:'DEF',club:'Dender'},
    {name:'Stephen Eustáquio',pos:'MID',club:'Los Angeles FC'},
    {name:'Ismaël Koné',pos:'MID',club:'Sassuolo'},
    {name:'Jonathan Osorio',pos:'MID',club:'Toronto FC'},
    {name:'Tajon Buchanan',pos:'MID',club:'Villarreal'},
    {name:'Liam Millar',pos:'MID',club:'Hull City'},
    {name:'Jacob Shaffelburg',pos:'MID',club:'Los Angeles FC'},
    {name:'Mathieu Choinière',pos:'MID',club:'Los Angeles FC'},
    {name:'Ali Ahmed',pos:'MID',club:'Norwich City'},
    {name:'Jonathan David',pos:'FWD',club:'Juventus'},
    {name:'Cyle Larin',pos:'FWD',club:'Southampton'},
    {name:'Tani Oluwaseyi',pos:'FWD',club:'Villarreal'}
  ],
  'Katar': [
    {name:'Meshaal Barsham',pos:'GK',club:'Al-Sadd'},
    {name:'Salah Zakaria',pos:'GK',club:'Al-Duhail'},
    {name:'Mahmud Abunada',pos:'GK',club:'Al-Rayyan'},
    {name:'Boualem Khoukhi',pos:'DEF',club:'Al-Sadd'},
    {name:'Pedro Miguel',pos:'DEF',club:'Al-Sadd'},
    {name:'Homam Ahmed',pos:'DEF',club:'Cultural Leonesa'},
    {name:'Lucas Mendes',pos:'DEF',club:'Al-Wakrah'},
    {name:'Sultan Al-Brake',pos:'DEF',club:'Al-Duhail'},
    {name:'Abdulaziz Hatem',pos:'MID',club:'Al-Rayyan'},
    {name:'Karim Boudiaf',pos:'MID',club:'Al-Duhail'},
    {name:'Assim Madibo',pos:'MID',club:'Al-Wakrah'},
    {name:'Ahmed Fathy',pos:'MID',club:'Al-Arabi'},
    {name:'Jassem Gaber',pos:'MID',club:'Al-Rayyan'},
    {name:'Hassan Al-Haydos',pos:'FWD',club:'Al-Sadd'},
    {name:'Akram Afif',pos:'FWD',club:'Al-Sadd'},
    {name:'Almoez Ali',pos:'FWD',club:'Al-Duhail'},
    {name:'Mohammed Muntari',pos:'FWD',club:'Al-Gharafa'},
    {name:'Ahmed Alaaeldin',pos:'FWD',club:'Al-Rayyan'},
    {name:'Yusuf Abdurisag',pos:'FWD',club:'Al-Wakrah'}
  ],
  'Schweiz': [
    {name:'Gregor Kobel',pos:'GK',club:'Borussia Dortmund'},
    {name:'Yvon Mvogo',pos:'GK',club:'Lorient'},
    {name:'Jonas Omlin',pos:'GK',club:'Monaco'},
    {name:'Silvan Widmer',pos:'DEF',club:'Mainz 05'},
    {name:'Ricardo Rodriguez',pos:'DEF',club:'Real Betis'},
    {name:'Miro Muheim',pos:'DEF',club:'Hamburger SV'},
    {name:'Eray Cömert',pos:'DEF',club:'Valencia'},
    {name:'Aurèle Amenda',pos:'DEF',club:'Eintracht Frankfurt'},
    {name:'Luca Jaquez',pos:'DEF',club:'VfB Stuttgart'},
    {name:'Granit Xhaka',pos:'MID',club:'Sunderland'},
    {name:'Remo Freuler',pos:'MID',club:'Nottingham Forest'},
    {name:'Djibril Sow',pos:'MID',club:'Sevilla'},
    {name:'Ardon Jashari',pos:'MID',club:'Milan'},
    {name:'Johan Manzambi',pos:'MID',club:'SC Freiburg'},
    {name:'Christian Fassnacht',pos:'MID',club:'Young Boys'},
    {name:'Rubén Vargas',pos:'FWD',club:'Sevilla'},
    {name:'Dan Ndoye',pos:'FWD',club:'Nottingham Forest'},
    {name:'Breel Embolo',pos:'FWD',club:'Monaco'},
    {name:'Cedric Itten',pos:'FWD',club:'Fortuna Düsseldorf'},
    {name:'Zeki Amdouni',pos:'FWD',club:'Burnley'}
  ],
  'Brasilien': [
    {name:'Alisson',pos:'GK',club:'Liverpool'},
    {name:'Ederson',pos:'GK',club:'Fenerbahçe'},
    {name:'Weverton',pos:'GK',club:'Grêmio'},
    {name:'Marquinhos',pos:'DEF',club:'Paris Saint-Germain'},
    {name:'Danilo Luiz',pos:'DEF',club:'Flamengo'},
    {name:'Alex Sandro',pos:'DEF',club:'Flamengo'},
    {name:'Gabriel Magalhães',pos:'DEF',club:'Arsenal'},
    {name:'Bremer',pos:'DEF',club:'Juventus'},
    {name:'Wesley',pos:'DEF',club:'Roma'},
    {name:'Léo Pereira',pos:'DEF',club:'Flamengo'},
    {name:'Casemiro',pos:'MID',club:'Manchester Utd'},
    {name:'Lucas Paquetá',pos:'MID',club:'Flamengo'},
    {name:'Bruno Guimarães',pos:'MID',club:'Newcastle Utd'},
    {name:'Fabinho',pos:'MID',club:'Al-Ittihad'},
    {name:'Neymar',pos:'FWD',club:'Santos'},
    {name:'Vinícius Júnior',pos:'FWD',club:'Real Madrid'},
    {name:'Raphinha',pos:'FWD',club:'Barcelona'},
    {name:'Gabriel Martinelli',pos:'FWD',club:'Arsenal'},
    {name:'Matheus Cunha',pos:'FWD',club:'Manchester Utd'},
    {name:'Endrick',pos:'FWD',club:'Lyon'},
    {name:'Luiz Henrique',pos:'FWD',club:'Zenit'},
    {name:'Rayan',pos:'FWD',club:'Bournemouth'}
  ],
  'Haiti': [
    {name:'Johny Placide',pos:'GK',club:'Bastia'},
    {name:'Alexandre Pierre',pos:'GK',club:'Sochaux'},
    {name:'Josué Duverger',pos:'GK',club:'Cosmos Koblenz'},
    {name:'Ricardo Adé',pos:'DEF',club:'LDU Quito'},
    {name:'Carlens Arcus',pos:'DEF',club:'Angers'},
    {name:'Martin Expérience',pos:'DEF',club:'Nancy'},
    {name:'Jean-Kévin Duverne',pos:'DEF',club:'Gent'},
    {name:'Duke Lacroix',pos:'DEF',club:'Colorado Springs Switchbacks'},
    {name:'Leverton Pierre',pos:'MID',club:'Vizela'},
    {name:'Danley Jean Jacques',pos:'MID',club:'Philadelphia Union'},
    {name:'Carl Sainté',pos:'MID',club:'El Paso Locomotive'},
    {name:'Jean-Ricner Bellegarde',pos:'MID',club:'Wolverhampton'},
    {name:'Duckens Nazon',pos:'FWD',club:'Esteghlal'},
    {name:'Frantzdy Pierrot',pos:'FWD',club:'Çaykur Rizespor'},
    {name:'Derrick Etienne Jr.',pos:'FWD',club:'Toronto FC'},
    {name:'Louicius Deedson',pos:'FWD',club:'FC Dallas'},
    {name:'Ruben Providence',pos:'FWD',club:'Almere City'},
    {name:'Wilson Isidor',pos:'FWD',club:'Sunderland'}
  ],
  'Marokko': [
    {name:'Yassine Bounou',pos:'GK',club:'Al-Hilal'},
    {name:'Munir Mohamedi',pos:'GK',club:'RS Berkane'},
    {name:'Ahmed Reda Tagnaouti',pos:'GK',club:'AS FAR'},
    {name:'Achraf Hakimi',pos:'DEF',club:'Paris Saint-Germain'},
    {name:'Nayef Aguerd',pos:'DEF',club:'Marseille'},
    {name:'Noussair Mazraoui',pos:'DEF',club:'Manchester Utd'},
    {name:'Youssef Belammari',pos:'DEF',club:'Al Ahly'},
    {name:'Anass Salah-Eddine',pos:'DEF',club:'PSV Eindhoven'},
    {name:'Chadi Riad',pos:'DEF',club:'Crystal Palace'},
    {name:'Issa Diop',pos:'DEF',club:'Fulham'},
    {name:'Sofyan Amrabat',pos:'MID',club:'Real Betis'},
    {name:'Azzedine Ounahi',pos:'MID',club:'Girona'},
    {name:'Bilal El Khannouss',pos:'MID',club:'VfB Stuttgart'},
    {name:'Ismael Saibari',pos:'MID',club:'PSV Eindhoven'},
    {name:'Neil El Aynaoui',pos:'MID',club:'Roma'},
    {name:'Ayoub El Kaabi',pos:'FWD',club:'Olympiakos'},
    {name:'Soufiane Rahimi',pos:'FWD',club:'Al Ain'},
    {name:'Abde Ezzalzouli',pos:'FWD',club:'Real Betis'},
    {name:'Brahim Díaz',pos:'FWD',club:'Real Madrid'},
    {name:'Youssef En-Nesyri',pos:'FWD',club:'Fenerbahçe'}
  ],
  'Schottland': [
    {name:'Craig Gordon',pos:'GK',club:'Heart of Midlothian'},
    {name:'Angus Gunn',pos:'GK',club:'Nottingham Forest'},
    {name:'Liam Kelly',pos:'GK',club:'Rangers'},
    {name:'Andy Robertson',pos:'DEF',club:'Liverpool'},
    {name:'Grant Hanley',pos:'DEF',club:'Hibernian'},
    {name:'Kieran Tierney',pos:'DEF',club:'Celtic'},
    {name:'Scott McKenna',pos:'DEF',club:'Dinamo Zagreb'},
    {name:'Jack Hendry',pos:'DEF',club:'Al-Ettifaq'},
    {name:'Nathan Patterson',pos:'DEF',club:'Everton'},
    {name:'Anthony Ralston',pos:'DEF',club:'Celtic'},
    {name:'Aaron Hickey',pos:'DEF',club:'Brentford'},
    {name:'John McGinn',pos:'MID',club:'Aston Villa'},
    {name:'Scott McTominay',pos:'MID',club:'Napoli'},
    {name:'Ryan Christie',pos:'MID',club:'Bournemouth'},
    {name:'Kenny McLean',pos:'MID',club:'Norwich City'},
    {name:'Billy Gilmour',pos:'MID',club:'Napoli'},
    {name:'Lewis Ferguson',pos:'MID',club:'Bologna'},
    {name:'Lyndon Dykes',pos:'FWD',club:'Charlton Athletic'},
    {name:'Ché Adams',pos:'FWD',club:'Torino'},
    {name:'Lawrence Shankland',pos:'FWD',club:'Heart of Midlothian'},
    {name:'George Hirst',pos:'FWD',club:'Ipswich Town'}
  ],
  'Australien': [
    {name:'Mat Ryan',pos:'GK',club:'Real Sociedad'},
    {name:'Danny Vukovic',pos:'GK',club:'Melbourne City'},
    {name:'Joe Gauci',pos:'GK',club:'Adelaide United'},
    {name:'Milos Degenek',pos:'DEF',club:'Red Bull Salzburg'},
    {name:'Harry Souttar',pos:'DEF',club:'Leicester City'},
    {name:'Aziz Behich',pos:'DEF',club:'Club Brügge'},
    {name:'Nathaniel Atkinson',pos:'DEF',club:'Heart of Midlothian'},
    {name:'Fran Karačić',pos:'DEF',club:'Brescia'},
    {name:'Kye Rowles',pos:'DEF',club:'Heart of Midlothian'},
    {name:'Aaron Mooy',pos:'MID',club:'Celtic'},
    {name:'Jackson Irvine',pos:'MID',club:'Middlesbrough'},
    {name:'Riley McGree',pos:'MID',club:'Middlesbrough'},
    {name:'Cameron Devlin',pos:'MID',club:'Heart of Midlothian'},
    {name:'Aiden O\'Neill',pos:'MID',club:'Coventry City'},
    {name:'Mitchell Duke',pos:'FWD',club:'FC Machida'},
    {name:'Martin Boyle',pos:'FWD',club:'Hibernian'},
    {name:'Mathew Leckie',pos:'FWD',club:'Melbourne City'},
    {name:'Jamie Maclaren',pos:'FWD',club:'Melbourne City'},
    {name:'Jason Cummings',pos:'FWD',club:'FC Machida'},
    {name:'Garang Kuol',pos:'FWD',club:'Hearts'}
  ],
  'Paraguay': [
    {name:'Gatito Fernández',pos:'GK',club:'Cerro Porteño'},
    {name:'Carlos Coronel',pos:'GK',club:'São Paulo'},
    {name:'Gustavo Gómez',pos:'DEF',club:'Palmeiras'},
    {name:'Júnior Alonso',pos:'DEF',club:'Atlético Mineiro'},
    {name:'Omar Alderete',pos:'DEF',club:'Getafe'},
    {name:'Fabián Balbuena',pos:'DEF',club:'Dinamo Moskau'},
    {name:'Blas Riveros',pos:'DEF',club:'Nordsjaelland'},
    {name:'Óscar Romero',pos:'MID',club:'Boca Juniors'},
    {name:'Miguel Almirón',pos:'MID',club:'Atlanta United'},
    {name:'Mathías Villasanti',pos:'MID',club:'Grêmio'},
    {name:'Andrés Cubas',pos:'MID',club:'Vancouver Whitecaps'},
    {name:'Ramón Sosa',pos:'MID',club:'Palmeiras'},
    {name:'Julio Enciso',pos:'FWD',club:'Strasbourg'},
    {name:'Gabriel Ávalos',pos:'FWD',club:'Independiente'},
    {name:'Adam Bareiro',pos:'FWD',club:'Boca Juniors'},
    {name:'Kaku',pos:'MID',club:'Al Ain'},
    {name:'Antonio Sanabria',pos:'FWD',club:'Torino'},
    {name:'Alex Arce',pos:'FWD',club:'Independiente Rivadavia'}
  ],
  'Türkei': [
    {name:'Uğurcan Çakır',pos:'GK',club:'Galatasaray'},
    {name:'Mert Günok',pos:'GK',club:'Fenerbahçe'},
    {name:'Altay Bayındır',pos:'GK',club:'Manchester Utd'},
    {name:'Merih Demiral',pos:'DEF',club:'Al-Ahli'},
    {name:'Zeki Çelik',pos:'DEF',club:'Roma'},
    {name:'Çağlar Söyüncü',pos:'DEF',club:'Fenerbahçe'},
    {name:'Samet Akaydin',pos:'DEF',club:'Çaykur Rizespor'},
    {name:'Hakan Çalhanoğlu',pos:'MID',club:'Inter Mailand'},
    {name:'Kaan Ayhan',pos:'MID',club:'Galatasaray'},
    {name:'Orkun Kökçü',pos:'MID',club:'Beşiktaş'},
    {name:'İsmail Yüksek',pos:'MID',club:'Fenerbahçe'},
    {name:'Salih Özcan',pos:'MID',club:'Borussia Dortmund'},
    {name:'Arda Güler',pos:'MID',club:'Real Madrid'},
    {name:'Kenan Yıldız',pos:'FWD',club:'Juventus'},
    {name:'Yunus Akgün',pos:'FWD',club:'Galatasaray'},
    {name:'Baris Alper Yilmaz',pos:'FWD',club:'Galatasaray'},
    {name:'Semih Kılıçsoy',pos:'FWD',club:'Besiktas'},
    {name:'Can Uzun',pos:'FWD',club:'Eintracht Frankfurt'}
  ],
  'USA': [
    {name:'Matt Turner',pos:'GK',club:'New England Revolution'},
    {name:'Matt Freese',pos:'GK',club:'New York City FC'},
    {name:'Chris Brady',pos:'GK',club:'Chicago Fire'},
    {name:'Sergiño Dest',pos:'DEF',club:'PSV Eindhoven'},
    {name:'Chris Richards',pos:'DEF',club:'Crystal Palace'},
    {name:'Antonee Robinson',pos:'DEF',club:'Fulham'},
    {name:'Mark McKenzie',pos:'DEF',club:'Toulouse'},
    {name:'Joe Scally',pos:'DEF',club:'Mönchengladbach'},
    {name:'Tyler Adams',pos:'MID',club:'Bournemouth'},
    {name:'Weston McKennie',pos:'MID',club:'Juventus'},
    {name:'Giovanni Reyna',pos:'MID',club:'Mönchengladbach'},
    {name:'Malik Tillman',pos:'MID',club:'Bayer Leverkusen'},
    {name:'Cristian Roldan',pos:'MID',club:'Seattle Sounders'},
    {name:'Sebastian Berhalter',pos:'MID',club:'Vancouver Whitecaps'},
    {name:'Alex Freeman',pos:'DEF',club:'Villarreal'},
    {name:'Christian Pulisic',pos:'FWD',club:'AC Milan'},
    {name:'Haji Wright',pos:'FWD',club:'Coventry City'},
    {name:'Folarin Balogun',pos:'FWD',club:'Monaco'},
    {name:'Timothy Weah',pos:'FWD',club:'Marseille'},
    {name:'Alejandro Zendejas',pos:'FWD',club:'América'}
  ],
  'Curaçao': [
    {name:'Eloy Room',pos:'GK',club:'Miami FC'},
    {name:'Shurandy Sambo',pos:'DEF',club:'Sparta Rotterdam'},
    {name:'Juriën Gaari',pos:'DEF',club:'Abha'},
    {name:'Armando Obispo',pos:'DEF',club:'PSV Eindhoven'},
    {name:'Joshua Brenet',pos:'DEF',club:'Kayserispor'},
    {name:'Riechedly Bazoer',pos:'DEF',club:'Konyaspor'},
    {name:'Leandro Bacuna',pos:'MID',club:'Iğdır'},
    {name:'Kevin Felida',pos:'MID',club:'Den Bosch'},
    {name:'Tyrese Noslin',pos:'MID',club:'Telstar'},
    {name:'Ar\'jany Martha',pos:'MID',club:'Rotherham Utd'},
    {name:'Sontje Hansen',pos:'FWD',club:'Middlesbrough'},
    {name:'Jeremy Antonisse',pos:'FWD',club:'Kifisia'},
    {name:'Jürgen Locadia',pos:'FWD',club:'Miami FC'},
    {name:'Kenji Gorré',pos:'FWD',club:'Maccabi Haifa'},
    {name:'Jearl Margaritha',pos:'FWD',club:'Beveren'},
    {name:'Brandley Kuwas',pos:'FWD',club:'Volendam'},
    {name:'Gervane Kastaneer',pos:'FWD',club:'Terengganu'},
    {name:'Tahith Chong',pos:'FWD',club:'Sheffield Utd'}
  ],
  'Ecuador': [
    {name:'Hernán Galíndez',pos:'GK',club:'Aucas'},
    {name:'Alexander Domínguez',pos:'GK',club:'Liga de Quito'},
    {name:'Moisés Ramírez',pos:'GK',club:'Independiente del Valle'},
    {name:'Piero Hincapié',pos:'DEF',club:'Bayer Leverkusen'},
    {name:'Ángelo Preciado',pos:'DEF',club:'Galatasaray'},
    {name:'Félix Torres',pos:'DEF',club:'Columbus Crew'},
    {name:'Diego Palacios',pos:'DEF',club:'Los Angeles FC'},
    {name:'Robert Arboleda',pos:'DEF',club:'São Paulo'},
    {name:'Stiven Mendez',pos:'DEF',club:'Aucas'},
    {name:'Carlos Gruezo',pos:'MID',club:'Augsburg'},
    {name:'Jhegson Méndez',pos:'MID',club:'LA Galaxy'},
    {name:'Moisés Caicedo',pos:'MID',club:'Chelsea'},
    {name:'Alan Minda',pos:'MID',club:'Midtjylland'},
    {name:'Jeremy Sarmiento',pos:'MID',club:'Sporting Lissabon'},
    {name:'Pervis Estupiñán',pos:'DEF',club:'Brighton'},
    {name:'Enner Valencia',pos:'FWD',club:'Internacional'},
    {name:'Michael Estrada',pos:'FWD',club:'Cruz Azul'},
    {name:'Djorkaeff Reasco',pos:'FWD',club:'Columbus Crew'},
    {name:'Kevin Rodríguez',pos:'FWD',club:'Ipswich Town'},
    {name:'John Yeboah',pos:'FWD',club:'Norwich City'}
  ],
  'Deutschland': [
    {name:'Manuel Neuer',pos:'GK',club:'Bayern München'},
    {name:'Oliver Baumann',pos:'GK',club:'TSG Hoffenheim'},
    {name:'Alexander Nübel',pos:'GK',club:'VfB Stuttgart'},
    {name:'Antonio Rüdiger',pos:'DEF',club:'Real Madrid'},
    {name:'Jonathan Tah',pos:'DEF',club:'Bayern München'},
    {name:'Nico Schlotterbeck',pos:'DEF',club:'Borussia Dortmund'},
    {name:'Waldemar Anton',pos:'DEF',club:'Borussia Dortmund'},
    {name:'David Raum',pos:'DEF',club:'RB Leipzig'},
    {name:'Malick Thiaw',pos:'DEF',club:'Newcastle Utd'},
    {name:'Nathaniel Brown',pos:'DEF',club:'Eintracht Frankfurt'},
    {name:'Joshua Kimmich',pos:'MID',club:'Bayern München'},
    {name:'Aleksandar Pavlović',pos:'MID',club:'Bayern München'},
    {name:'Leon Goretzka',pos:'MID',club:'Bayern München'},
    {name:'Jamal Musiala',pos:'MID',club:'Bayern München'},
    {name:'Florian Wirtz',pos:'MID',club:'Liverpool'},
    {name:'Leroy Sané',pos:'MID',club:'Galatasaray'},
    {name:'Pascal Groß',pos:'MID',club:'Brighton'},
    {name:'Angelo Stiller',pos:'MID',club:'VfB Stuttgart'},
    {name:'Felix Nmecha',pos:'MID',club:'Borussia Dortmund'},
    {name:'Lennart Karl',pos:'MID',club:'Bayern München'},
    {name:'Kai Havertz',pos:'FWD',club:'Arsenal'},
    {name:'Nick Woltemade',pos:'FWD',club:'Newcastle Utd'},
    {name:'Maximilian Beier',pos:'FWD',club:'Borussia Dortmund'},
    {name:'Jamie Leweling',pos:'FWD',club:'VfB Stuttgart'},
    {name:'Deniz Undav',pos:'FWD',club:'VfB Stuttgart'}
  ],
  'Elfenbeinküste': [
    {name:'Yahia Fofana',pos:'GK',club:'Çaykur Rizespor'},
    {name:'Alban Lafont',pos:'GK',club:'Panathinaikos'},
    {name:'Emmanuel Agbadou',pos:'DEF',club:'Beşiktaş'},
    {name:'Guéla Doué',pos:'DEF',club:'Strasbourg'},
    {name:'Ousmane Diomande',pos:'DEF',club:'Sporting CP'},
    {name:'Christopher Opéri',pos:'DEF',club:'İstanbul Başakşehir'},
    {name:'Serge Aurier',pos:'DEF',club:'Villarreal'},
    {name:'Franck Kessié',pos:'MID',club:'Al-Ahli'},
    {name:'Jean Michaël Seri',pos:'MID',club:'Maribor'},
    {name:'Ibrahim Sangaré',pos:'MID',club:'Nottingham Forest'},
    {name:'Seko Fofana',pos:'MID',club:'Porto'},
    {name:'Christ Inao Oulaï',pos:'MID',club:'Trabzonspor'},
    {name:'Nicolas Pépé',pos:'FWD',club:'Villarreal'},
    {name:'Oumar Diakité',pos:'FWD',club:'Cercle Brugge'},
    {name:'Simon Adingra',pos:'FWD',club:'Monaco'},
    {name:'Evann Guessand',pos:'FWD',club:'Crystal Palace'},
    {name:'Amad Diallo',pos:'FWD',club:'Manchester Utd'},
    {name:'Wilfried Zaha',pos:'FWD',club:'Galatasaray'}
  ],
  'Japan': [
    {name:'Zion Suzuki',pos:'GK',club:'Parma'},
    {name:'Keisuke Ōsako',pos:'GK',club:'Sanfrecce Hiroshima'},
    {name:'Tomoki Hayakawa',pos:'GK',club:'Kashima Antlers'},
    {name:'Yūto Nagatomo',pos:'DEF',club:'FC Tokyo'},
    {name:'Kō Itakura',pos:'DEF',club:'Ajax'},
    {name:'Takehiro Tomiyasu',pos:'DEF',club:'Ajax'},
    {name:'Hiroki Itō',pos:'DEF',club:'Bayern München'},
    {name:'Yukinari Sugawara',pos:'DEF',club:'Werder Bremen'},
    {name:'Shōgo Taniguchi',pos:'DEF',club:'Sint-Truiden'},
    {name:'Ayumu Seko',pos:'DEF',club:'Le Havre'},
    {name:'Tsuyoshi Watanabe',pos:'DEF',club:'Feyenoord'},
    {name:'Junnosuke Suzuki',pos:'DEF',club:'FC Kopenhagen'},
    {name:'Wataru Endo',pos:'MID',club:'Liverpool'},
    {name:'Ao Tanaka',pos:'MID',club:'Leeds Utd'},
    {name:'Takefusa Kubo',pos:'MID',club:'Real Sociedad'},
    {name:'Ritsu Dōan',pos:'MID',club:'Eintracht Frankfurt'},
    {name:'Junya Itō',pos:'MID',club:'Genk'},
    {name:'Daichi Kamada',pos:'MID',club:'Crystal Palace'},
    {name:'Keito Nakamura',pos:'MID',club:'Reims'},
    {name:'Kaishū Sano',pos:'MID',club:'Mainz 05'},
    {name:'Ayase Ueda',pos:'FWD',club:'Feyenoord'},
    {name:'Daizen Maeda',pos:'FWD',club:'Celtic'},
    {name:'Kōki Ogawa',pos:'FWD',club:'NEC'},
    {name:'Yuito Suzuki',pos:'FWD',club:'SC Freiburg'},
    {name:'Kento Shiogai',pos:'FWD',club:'VfL Wolfsburg'}
  ],
  'Niederlande': [
    {name:'Bart Verbruggen',pos:'GK',club:'Brighton'},
    {name:'Mark Flekken',pos:'GK',club:'Bayer Leverkusen'},
    {name:'Robin Roefs',pos:'GK',club:'Sunderland'},
    {name:'Virgil van Dijk',pos:'DEF',club:'Liverpool'},
    {name:'Denzel Dumfries',pos:'DEF',club:'Inter Mailand'},
    {name:'Nathan Aké',pos:'DEF',club:'Manchester City'},
    {name:'Jurriën Timber',pos:'DEF',club:'Arsenal'},
    {name:'Micky van de Ven',pos:'DEF',club:'Tottenham'},
    {name:'Daley Blind',pos:'DEF',club:'Girona'},
    {name:'Frenkie de Jong',pos:'MID',club:'Barcelona'},
    {name:'Tijjani Reijnders',pos:'MID',club:'AC Milan'},
    {name:'Ryan Gravenberch',pos:'MID',club:'Liverpool'},
    {name:'Xavi Simons',pos:'MID',club:'Paris Saint-Germain'},
    {name:'Guus Til',pos:'MID',club:'PSV Eindhoven'},
    {name:'Memphis Depay',pos:'FWD',club:'Corinthians'},
    {name:'Wout Weghorst',pos:'FWD',club:'Ajax'},
    {name:'Donyell Malen',pos:'FWD',club:'Roma'},
    {name:'Cody Gakpo',pos:'FWD',club:'Liverpool'},
    {name:'Noa Lang',pos:'FWD',club:'Galatasaray'},
    {name:'Brian Brobbey',pos:'FWD',club:'Sunderland'},
    {name:'Crysencio Summerville',pos:'FWD',club:'West Ham Utd'}
  ],
  'Schweden': [
    {name:'Jacob Widell Zetterström',pos:'GK',club:'Derby County'},
    {name:'Viktor Johansson',pos:'GK',club:'Stoke City'},
    {name:'Gustaf Lagerbielke',pos:'DEF',club:'Braga'},
    {name:'Carl Starfelt',pos:'DEF',club:'Celta Vigo'},
    {name:'Hjalmar Ekdal',pos:'DEF',club:'Burnley'},
    {name:'Daniel Svensson',pos:'DEF',club:'Borussia Dortmund'},
    {name:'Alexander Isak',pos:'FWD',club:'Liverpool'},
    {name:'Viktor Gyökeres',pos:'FWD',club:'Arsenal'},
    {name:'Anthony Elanga',pos:'FWD',club:'Newcastle Utd'},
    {name:'Benjamin Nygren',pos:'FWD',club:'Celtic'},
    {name:'Ken Sema',pos:'FWD',club:'Pafos'},
    {name:'Alexander Bernhardsson',pos:'FWD',club:'Holstein Kiel'},
    {name:'Jesper Karlström',pos:'MID',club:'Udinese'},
    {name:'Mattias Svanberg',pos:'MID',club:'VfL Wolfsburg'},
    {name:'Yasin Ayari',pos:'MID',club:'Brighton'},
    {name:'Dejan Kulusevski',pos:'MID',club:'Tottenham'},
    {name:'Besfort Zeneli',pos:'MID',club:'Union Saint-Gilloise'},
    {name:'Emil Holm',pos:'DEF',club:'Atalanta'},
    {name:'Herman Johansson',pos:'DEF',club:'Djurgårdens IF'}
  ],
  'Tunesien': [
    {name:'Aymen Dahmen',pos:'GK',club:'CS Sfaxien'},
    {name:'Sabri Ben Hessen',pos:'GK',club:'Étoile du Sahel'},
    {name:'Montassar Talbi',pos:'DEF',club:'Lorient'},
    {name:'Dylan Bronn',pos:'DEF',club:'Servette'},
    {name:'Ali Abdi',pos:'DEF',club:'Nice'},
    {name:'Yan Valery',pos:'DEF',club:'Young Boys'},
    {name:'Omar Rekik',pos:'DEF',club:'Maribor'},
    {name:'Ellyes Skhiri',pos:'MID',club:'Eintracht Frankfurt'},
    {name:'Hannibal Mejbri',pos:'MID',club:'Burnley'},
    {name:'Anis Ben Slimane',pos:'MID',club:'Norwich City'},
    {name:'Ismaël Gharbi',pos:'MID',club:'FC Augsburg'},
    {name:'Rani Khedira',pos:'MID',club:'Union Berlin'},
    {name:'Elias Achouri',pos:'FWD',club:'FC Kopenhagen'},
    {name:'Firas Chaouat',pos:'FWD',club:'Club Africain'},
    {name:'Hazem Mastouri',pos:'FWD',club:'Dynamo Machatschkala'},
    {name:'Elias Saad',pos:'FWD',club:'Hannover 96'},
    {name:'Sebastian Tounekti',pos:'FWD',club:'Celtic'},
    {name:'Seifeddine Jaziri',pos:'FWD',club:'Trabzonspor'},
    {name:'Saif-Eddine Khaoui',pos:'FWD',club:'Sivasspor'}
  ],
  'Belgien': [
    {name:'Thibaut Courtois',pos:'GK',club:'Real Madrid'},
    {name:'Senne Lammens',pos:'GK',club:'Manchester Utd'},
    {name:'Mike Penders',pos:'GK',club:'Strasbourg'},
    {name:'Thomas Meunier',pos:'DEF',club:'Lille'},
    {name:'Timothy Castagne',pos:'DEF',club:'Fulham'},
    {name:'Arthur Theate',pos:'DEF',club:'Eintracht Frankfurt'},
    {name:'Zeno Debast',pos:'DEF',club:'Sporting CP'},
    {name:'Maxim De Cuyper',pos:'DEF',club:'Brighton'},
    {name:'Brandon Mechele',pos:'DEF',club:'Club Brügge'},
    {name:'Axel Witsel',pos:'MID',club:'Girona'},
    {name:'Kevin De Bruyne',pos:'MID',club:'Napoli'},
    {name:'Youri Tielemans',pos:'MID',club:'Aston Villa'},
    {name:'Hans Vanaken',pos:'MID',club:'Club Brügge'},
    {name:'Amadou Onana',pos:'MID',club:'Aston Villa'},
    {name:'Nicolas Raskin',pos:'MID',club:'Rangers'},
    {name:'Romelu Lukaku',pos:'FWD',club:'Napoli'},
    {name:'Leandro Trossard',pos:'FWD',club:'Arsenal'},
    {name:'Jérémy Doku',pos:'FWD',club:'Manchester City'},
    {name:'Dodi Lukébakio',pos:'FWD',club:'Benfica'},
    {name:'Charles De Ketelaere',pos:'FWD',club:'Atalanta'},
    {name:'Alexis Saelemaekers',pos:'FWD',club:'Milan'}
  ],
  'Ägypten': [
    {name:'Mohamed El Shenawy',pos:'GK',club:'Al Ahly'},
    {name:'Mostafa Shobeir',pos:'GK',club:'Al Ahly'},
    {name:'Hamdy Fathy',pos:'DEF',club:'Al-Wakrah'},
    {name:'Ramy Rabia',pos:'DEF',club:'Al Ain'},
    {name:'Mohamed Hany',pos:'DEF',club:'Al Ahly'},
    {name:'Ahmed Fatouh',pos:'DEF',club:'Zamalek'},
    {name:'Mohamed Abdelmonem',pos:'DEF',club:'Nice'},
    {name:'Hossam Abdelmaguid',pos:'DEF',club:'Zamalek'},
    {name:'Marwan Attia',pos:'MID',club:'Al Ahly'},
    {name:'Emam Ashour',pos:'MID',club:'Al Ahly'},
    {name:'Mohanad Lasheen',pos:'MID',club:'Pyramids'},
    {name:'Nabil Emad',pos:'MID',club:'Al-Najma'},
    {name:'Mohamed Salah',pos:'FWD',club:'Liverpool'},
    {name:'Trézéguet',pos:'FWD',club:'Al Ahly'},
    {name:'Zizo',pos:'FWD',club:'Al Ahly'},
    {name:'Omar Marmoush',pos:'FWD',club:'Manchester City'},
    {name:'Ibrahim Adel',pos:'FWD',club:'Nordsjælland'},
    {name:'Mahmoud Trezeguet',pos:'FWD',club:'Al Ahly'}
  ],
  'Iran': [
    {name:'Alireza Beiranvand',pos:'GK',club:'Tractor'},
    {name:'Payam Niazmand',pos:'GK',club:'Persepolis'},
    {name:'Hossein Hosseini',pos:'GK',club:'Sepahan'},
    {name:'Ehsan Hajsafi',pos:'DEF',club:'Sepahan'},
    {name:'Milad Mohammadi',pos:'DEF',club:'Persepolis'},
    {name:'Ramin Rezaeian',pos:'DEF',club:'Foolad'},
    {name:'Hossein Kanaanizadegan',pos:'DEF',club:'Persepolis'},
    {name:'Shojae Khalilzadeh',pos:'DEF',club:'Tractor'},
    {name:'Saleh Hardani',pos:'DEF',club:'Esteghlal'},
    {name:'Alireza Jahanbakhsh',pos:'MID',club:'Dender'},
    {name:'Saeid Ezatolahi',pos:'MID',club:'Shabab Al-Ahli'},
    {name:'Saman Ghoddos',pos:'MID',club:'Kalba'},
    {name:'Mehdi Torabi',pos:'MID',club:'Tractor'},
    {name:'Rouzbeh Cheshmi',pos:'MID',club:'Esteghlal'},
    {name:'Mohammad Mohebi',pos:'MID',club:'Rostov'},
    {name:'Mehdi Taremi',pos:'FWD',club:'Olympiakos'},
    {name:'Mehdi Ghayedi',pos:'FWD',club:'Al-Nasr'},
    {name:'Amirhossein Hosseinzadeh',pos:'FWD',club:'Tractor'},
    {name:'Ali Alipour',pos:'FWD',club:'Persepolis'},
    {name:'Sardar Azmoun',pos:'FWD',club:'Bayer Leverkusen'}
  ],
  'Neuseeland': [
    {name:'Michael Woud',pos:'GK',club:'Auckland FC'},
    {name:'Alex Paulsen',pos:'GK',club:'Lechia Gdańsk'},
    {name:'Chris Wood',pos:'FWD',club:'Nottingham Forest'},
    {name:'Sarpreet Singh',pos:'MID',club:'Wellington Phoenix'},
    {name:'Elijah Just',pos:'MID',club:'Motherwell'},
    {name:'Liberato Cacace',pos:'DEF',club:'Wrexham'},
    {name:'Nando Pijnaker',pos:'DEF',club:'Auckland FC'},
    {name:'Tommy Smith',pos:'DEF',club:'Braintree Town'},
    {name:'Finn Surman',pos:'DEF',club:'Portland Timbers'},
    {name:'Alex Rufer',pos:'MID',club:'Wellington Phoenix'},
    {name:'Kosta Barbarouses',pos:'FWD',club:'Western Sydney Wanderers'},
    {name:'Ben Waine',pos:'FWD',club:'Port Vale'},
    {name:'Ben Old',pos:'MID',club:'Saint-Étienne'},
    {name:'Callum McCowatt',pos:'MID',club:'Silkeborg'},
    {name:'Jesse Randall',pos:'FWD',club:'Auckland FC'},
    {name:'Ryan Thomas',pos:'MID',club:'PEC Zwolle'},
    {name:'Callan Elliot',pos:'DEF',club:'Auckland FC'},
    {name:'Lachlan Bayliss',pos:'MID',club:'Newcastle Jets'}
  ],
  'Kap Verde': [
    {name:'Vozinha',pos:'GK',club:'Chaves'},
    {name:'Márcio Rosa',pos:'GK',club:'Montana'},
    {name:'CJ dos Santos',pos:'GK',club:'San Diego FC'},
    {name:'Stopira',pos:'DEF',club:'Torreense'},
    {name:'Roberto Lopes',pos:'DEF',club:'Shamrock Rovers'},
    {name:'João Paulo',pos:'DEF',club:'FCSB'},
    {name:'Diney',pos:'DEF',club:'Al Bataeh'},
    {name:'Logan Costa',pos:'DEF',club:'Villarreal'},
    {name:'Steven Moreira',pos:'DEF',club:'Columbus Crew'},
    {name:'Wagner Pina',pos:'DEF',club:'Trabzonspor'},
    {name:'Jamiro Monteiro',pos:'MID',club:'PEC Zwolle'},
    {name:'Kevin Pina',pos:'MID',club:'Krasnodar'},
    {name:'Deroy Duarte',pos:'MID',club:'Ludogorets'},
    {name:'Telmo Arcanjo',pos:'MID',club:'Vitória de Guimarães'},
    {name:'Laros Duarte',pos:'MID',club:'Puskás Akadémia'},
    {name:'Ryan Mendes',pos:'FWD',club:'Iğdır'},
    {name:'Garry Rodrigues',pos:'FWD',club:'Apollon Limassol'},
    {name:'Willy Semedo',pos:'FWD',club:'Omonia'},
    {name:'Jovane Cabral',pos:'FWD',club:'Estrela Amadora'},
    {name:'Dailon Livramento',pos:'FWD',club:'Casa Pia'}
  ],
  'Saudi-Arabien': [
    {name:'Mohammed Al-Owais',pos:'GK',club:'Al-Hilal'},
    {name:'Yasser Al-Mosailem',pos:'GK',club:'Al-Hilal'},
    {name:'Saud Abdulhamid',pos:'DEF',club:'Lens'},
    {name:'Hassan Al-Tambakti',pos:'DEF',club:'Al-Hilal'},
    {name:'Abdulelah Al-Amri',pos:'DEF',club:'Al-Nassr'},
    {name:'Nawaf Boushal',pos:'DEF',club:'Al-Nassr'},
    {name:'Ali Lajami',pos:'DEF',club:'Al-Hilal'},
    {name:'Hassan Kadesh',pos:'DEF',club:'Al-Ittihad'},
    {name:'Salem Al-Dawsari',pos:'MID',club:'Al-Hilal'},
    {name:'Mohamed Kanno',pos:'MID',club:'Al-Hilal'},
    {name:'Nasser Al-Dawsari',pos:'MID',club:'Al-Hilal'},
    {name:'Abdullah Al-Khaibari',pos:'MID',club:'Al-Nassr'},
    {name:'Musab Al-Juwayr',pos:'MID',club:'Al-Qadsiah'},
    {name:'Saleh Alshehri',pos:'FWD',club:'Al-Hilal'},
    {name:'Firas Al-Buraikan',pos:'FWD',club:'Al-Ahli'},
    {name:'Nasser Al-Dawsari',pos:'FWD',club:'Al-Hilal'},
    {name:'Mohammed Al-Buraikan',pos:'FWD',club:'Al-Feiha'},
    {name:'Khalid Al-Ghannam',pos:'FWD',club:'Al-Ettifaq'}
  ],
  'Spanien': [
    {name:'Unai Simón',pos:'GK',club:'Athletic Bilbao'},
    {name:'David Raya',pos:'GK',club:'Arsenal'},
    {name:'Joan Garcia',pos:'GK',club:'Barcelona'},
    {name:'Aymeric Laporte',pos:'DEF',club:'Athletic Bilbao'},
    {name:'Marc Cucurella',pos:'DEF',club:'Chelsea'},
    {name:'Marcos Llorente',pos:'DEF',club:'Atlético Madrid'},
    {name:'Eric García',pos:'DEF',club:'Barcelona'},
    {name:'Pedro Porro',pos:'DEF',club:'Tottenham'},
    {name:'Álex Grimaldo',pos:'DEF',club:'Bayer Leverkusen'},
    {name:'Pau Cubarsí',pos:'DEF',club:'Barcelona'},
    {name:'Marc Pubill',pos:'DEF',club:'Atlético Madrid'},
    {name:'Rodri',pos:'MID',club:'Manchester City'},
    {name:'Mikel Merino',pos:'MID',club:'Arsenal'},
    {name:'Fabián Ruiz',pos:'MID',club:'Paris Saint-Germain'},
    {name:'Pedri',pos:'MID',club:'Barcelona'},
    {name:'Gavi',pos:'MID',club:'Barcelona'},
    {name:'Martín Zubimendi',pos:'MID',club:'Arsenal'},
    {name:'Ferran Torres',pos:'FWD',club:'Barcelona'},
    {name:'Mikel Oyarzabal',pos:'FWD',club:'Real Sociedad'},
    {name:'Dani Olmo',pos:'FWD',club:'Barcelona'},
    {name:'Nico Williams',pos:'FWD',club:'Athletic Bilbao'},
    {name:'Lamine Yamal',pos:'FWD',club:'Barcelona'},
    {name:'Yéremy Pino',pos:'FWD',club:'Crystal Palace'}
  ],
  'Uruguay': [
    {name:'Sergio Rochet',pos:'GK',club:'Nacional'},
    {name:'Fernando Muslera',pos:'GK',club:'Galatasaray'},
    {name:'Guillermo Varela',pos:'DEF',club:'Flamengo'},
    {name:'Diego Godín',pos:'DEF',club:'Vélez Sarsfield'},
    {name:'Sebastián Coates',pos:'DEF',club:'Sporting CP'},
    {name:'José María Giménez',pos:'DEF',club:'Atlético Madrid'},
    {name:'Matías Viña',pos:'DEF',club:'Roma'},
    {name:'Ronald Araújo',pos:'DEF',club:'Barcelona'},
    {name:'Facundo Pellistri',pos:'DEF',club:'Manchester Utd'},
    {name:'Federico Valverde',pos:'MID',club:'Real Madrid'},
    {name:'Rodrigo Bentancur',pos:'MID',club:'Tottenham'},
    {name:'Nicolás de la Cruz',pos:'MID',club:'Flamengo'},
    {name:'Manuel Ugarte',pos:'MID',club:'Manchester Utd'},
    {name:'Lucas Torreira',pos:'MID',club:'Galatasaray'},
    {name:'Giorgian De Arrascaeta',pos:'MID',club:'Flamengo'},
    {name:'Luis Suárez',pos:'FWD',club:'Inter Miami'},
    {name:'Edinson Cavani',pos:'FWD',club:'Independiente'},
    {name:'Darwin Núñez',pos:'FWD',club:'Liverpool'},
    {name:'Maximiliano Gómez',pos:'FWD',club:'Sporting CP'},
    {name:'Facundo Torres',pos:'FWD',club:'Orlando City'}
  ],
  'Frankreich': [
    {name:'Brice Samba',pos:'GK',club:'Rennes'},
    {name:'Mike Maignan',pos:'GK',club:'Milan'},
    {name:'Alphonse Areola',pos:'GK',club:'West Ham Utd'},
    {name:'Malo Gusto',pos:'DEF',club:'Chelsea'},
    {name:'Lucas Digne',pos:'DEF',club:'Aston Villa'},
    {name:'Dayot Upamecano',pos:'DEF',club:'Bayern München'},
    {name:'Jules Koundé',pos:'DEF',club:'Barcelona'},
    {name:'Ibrahima Konaté',pos:'DEF',club:'Liverpool'},
    {name:'William Saliba',pos:'DEF',club:'Arsenal'},
    {name:'Théo Hernandez',pos:'DEF',club:'Al-Hilal'},
    {name:'Aurélien Tchouaméni',pos:'MID',club:'Real Madrid'},
    {name:'N\'Golo Kanté',pos:'MID',club:'Fenerbahçe'},
    {name:'Adrien Rabiot',pos:'MID',club:'Milan'},
    {name:'Manu Koné',pos:'MID',club:'Roma'},
    {name:'Warren Zaïre-Emery',pos:'MID',club:'Paris Saint-Germain'},
    {name:'Kylian Mbappé',pos:'FWD',club:'Real Madrid'},
    {name:'Ousmane Dembélé',pos:'FWD',club:'Paris Saint-Germain'},
    {name:'Marcus Thuram',pos:'FWD',club:'Inter Mailand'},
    {name:'Michael Olise',pos:'FWD',club:'Bayern München'},
    {name:'Bradley Barcola',pos:'FWD',club:'Paris Saint-Germain'}
  ],
  'Irak': [
    {name:'Jalal Hassan',pos:'GK',club:'Al-Zawraa'},
    {name:'Fahad Talib',pos:'GK',club:'Al-Talaba'},
    {name:'Ahmed Basil',pos:'GK',club:'Al-Shorta'},
    {name:'Rebin Sulaka',pos:'DEF',club:'Port FC'},
    {name:'Manaf Younis',pos:'DEF',club:'Al-Shorta'},
    {name:'Merchas Doski',pos:'DEF',club:'Viktoria Plzeň'},
    {name:'Hussein Ali',pos:'DEF',club:'Pogoń Szczecin'},
    {name:'Zaid Tahseen',pos:'DEF',club:'Pakhtakor'},
    {name:'Frans Putros',pos:'DEF',club:'Persib'},
    {name:'Ibrahim Bayesh',pos:'MID',club:'Al-Dhafra'},
    {name:'Amir Al-Ammari',pos:'MID',club:'Cracovia'},
    {name:'Ali Jasim',pos:'MID',club:'Al-Najma'},
    {name:'Youssef Amyn',pos:'MID',club:'AEK Larnaca'},
    {name:'Zidane Iqbal',pos:'MID',club:'FC Utrecht'},
    {name:'Hasan Abdulkareem',pos:'MID',club:'Al-Zawraa'},
    {name:'Aymen Hussein',pos:'FWD',club:'Al-Karma'},
    {name:'Mohanad Ali',pos:'FWD',club:'Dibba'},
    {name:'Ali Al-Hamadi',pos:'FWD',club:'Luton Town'},
    {name:'Amar Al-Daqqaq',pos:'FWD',club:'Al-Shorta'}
  ],
  'Norwegen': [
    {name:'Ørjan Nyland',pos:'GK',club:'Sevilla'},
    {name:'Egil Selvik',pos:'GK',club:'Watford'},
    {name:'Sander Tangvik',pos:'GK',club:'Hamburger SV'},
    {name:'Kristoffer Ajer',pos:'DEF',club:'Brentford'},
    {name:'Leo Østigård',pos:'DEF',club:'Genua'},
    {name:'David Møller Wolfe',pos:'DEF',club:'Wolverhampton'},
    {name:'Alexander Sørloth',pos:'FWD',club:'Atlético Madrid'},
    {name:'Sander Berge',pos:'MID',club:'Fulham'},
    {name:'Erling Haaland',pos:'FWD',club:'Manchester City'},
    {name:'Martin Ødegaard',pos:'MID',club:'Arsenal'},
    {name:'Jørgen Strand Larsen',pos:'FWD',club:'Crystal Palace'},
    {name:'Morten Thorsby',pos:'MID',club:'Cremonese'},
    {name:'Patrick Berg',pos:'MID',club:'Bodø/Glimt'},
    {name:'Julian Ryerson',pos:'DEF',club:'Borussia Dortmund'},
    {name:'Marcus Holmgren Pedersen',pos:'DEF',club:'Feyenoord'},
    {name:'Tobias Svendsen',pos:'MID',club:'Bodø/Glimt'},
    {name:'Mathias Normann',pos:'MID',club:'Bodø/Glimt'},
    {name:'Mohamed Elyounoussi',pos:'FWD',club:'Celtic'},
    {name:'Ola Solbakken',pos:'FWD',club:'Roma'}
  ],
  'Senegal': [
    {name:'Édouard Mendy',pos:'GK',club:'Al-Ahli'},
    {name:'Mory Diaw',pos:'GK',club:'Le Havre'},
    {name:'Yehvann Diouf',pos:'GK',club:'Nice'},
    {name:'Kalidou Koulibaly',pos:'DEF',club:'Al-Hilal'},
    {name:'Krépin Diatta',pos:'DEF',club:'Monaco'},
    {name:'Moussa Niakhaté',pos:'DEF',club:'Lyon'},
    {name:'Ismail Jakobs',pos:'DEF',club:'Galatasaray'},
    {name:'El Hadji Malick Diouf',pos:'DEF',club:'West Ham Utd'},
    {name:'Mamadou Sarr',pos:'DEF',club:'Chelsea'},
    {name:'Idrissa Gueye',pos:'MID',club:'Everton'},
    {name:'Pape Gueye',pos:'MID',club:'Villarreal'},
    {name:'Pape Matar Sarr',pos:'MID',club:'Tottenham'},
    {name:'Lamine Camara',pos:'MID',club:'Monaco'},
    {name:'Habib Diarra',pos:'MID',club:'Sunderland'},
    {name:'Pathé Ciss',pos:'MID',club:'Rayo Vallecano'},
    {name:'Sadio Mané',pos:'FWD',club:'Al-Nassr'},
    {name:'Ismaïla Sarr',pos:'FWD',club:'Crystal Palace'},
    {name:'Iliman Ndiaye',pos:'FWD',club:'Everton'},
    {name:'Nicolas Jackson',pos:'FWD',club:'Bayern München'},
    {name:'Bamba Dieng',pos:'FWD',club:'Lorient'},
    {name:'Assane Diao',pos:'FWD',club:'Como'}
  ],
  'Algerien': [
    {name:'Rais Mbolhi',pos:'GK',club:'Angers'},
    {name:'Alexandre Oukidja',pos:'GK',club:'Metz'},
    {name:'Aissa Mandi',pos:'DEF',club:'Villarreal'},
    {name:'Ramy Bensebaini',pos:'DEF',club:'Borussia Dortmund'},
    {name:'Djamel Benlamri',pos:'DEF',club:'Trabzonspor'},
    {name:'Andy Delort',pos:'FWD',club:'Nice'},
    {name:'Sofiane Feghouli',pos:'MID',club:'Galatasaray'},
    {name:'Haris Belkebla',pos:'MID',club:'Clermont'},
    {name:'Samir Beloufa',pos:'MID',club:'Metz'},
    {name:'Said Benrahma',pos:'MID',club:'Lyon'},
    {name:'Ryad Mahrez',pos:'MID',club:'Al-Ahli'},
    {name:'Islam Slimani',pos:'FWD',club:'Angers'},
    {name:'Youcef Atal',pos:'DEF',club:'Nice'},
    {name:'Nabil Bentaleb',pos:'MID',club:'Swansea'},
    {name:'Mohamed Amoura',pos:'FWD',club:'VfB Stuttgart'},
    {name:'Billal Brahimi',pos:'MID',club:'Porto'},
    {name:'Farès Chaïbi',pos:'MID',club:'Eintracht Frankfurt'},
    {name:'Djamel Eddine Benali',pos:'MID',club:'Lens'}
  ],
  'Ghana': [
    {name:'Lawrence Ati-Zigi',pos:'GK',club:'St. Gallen'},
    {name:'Benjamin Asare',pos:'GK',club:'Hearts of Oak'},
    {name:'Abdul Rahman Baba',pos:'DEF',club:'PAOK'},
    {name:'Gideon Mensah',pos:'DEF',club:'Auxerre'},
    {name:'Alexander Djiku',pos:'DEF',club:'Spartak Moskau'},
    {name:'Alidu Seidu',pos:'DEF',club:'Rennes'},
    {name:'Abdul Mumin',pos:'DEF',club:'Rayo Vallecano'},
    {name:'Jerome Opoku',pos:'DEF',club:'İstanbul Başakşehir'},
    {name:'Thomas Partey',pos:'MID',club:'Villarreal'},
    {name:'Abdul Fatawu',pos:'MID',club:'Leicester City'},
    {name:'Kamaldeen Sulemana',pos:'MID',club:'Atalanta'},
    {name:'Elisha Owusu',pos:'MID',club:'Auxerre'},
    {name:'Jordan Ayew',pos:'FWD',club:'Leicester City'},
    {name:'Antoine Semenyo',pos:'FWD',club:'Manchester City'},
    {name:'Iñaki Williams',pos:'FWD',club:'Athletic Bilbao'},
    {name:'Ernest Nuamah',pos:'FWD',club:'Lyon'},
    {name:'Mohammed Kudus',pos:'MID',club:'West Ham Utd'},
    {name:'Caleb Yirenkyi',pos:'MID',club:'Nordsjælland'}
  ],
  'Argentinien': [
    {name:'Emiliano Martínez',pos:'GK',club:'Aston Villa'},
    {name:'Juan Musso',pos:'GK',club:'Atlético Madrid'},
    {name:'Gerónimo Rulli',pos:'GK',club:'Marseille'},
    {name:'Leonardo Balerdi',pos:'DEF',club:'Marseille'},
    {name:'Nicolás Tagliafico',pos:'DEF',club:'Lyon'},
    {name:'Gonzalo Montiel',pos:'DEF',club:'River Plate'},
    {name:'Lisandro Martínez',pos:'DEF',club:'Manchester Utd'},
    {name:'Cristian Romero',pos:'DEF',club:'Tottenham'},
    {name:'Nicolás Otamendi',pos:'DEF',club:'Benfica'},
    {name:'Nahuel Molina',pos:'DEF',club:'Atlético Madrid'},
    {name:'Facundo Medina',pos:'DEF',club:'Marseille'},
    {name:'Leandro Paredes',pos:'MID',club:'Boca Juniors'},
    {name:'Rodrigo De Paul',pos:'MID',club:'Inter Miami'},
    {name:'Alexis Mac Allister',pos:'MID',club:'Liverpool'},
    {name:'Enzo Fernández',pos:'MID',club:'Chelsea'},
    {name:'Exequiel Palacios',pos:'MID',club:'Bayer Leverkusen'},
    {name:'Giovani Lo Celso',pos:'MID',club:'Real Betis'},
    {name:'Lionel Messi',pos:'FWD',club:'Inter Miami'},
    {name:'Julián Alvarez',pos:'FWD',club:'Atlético Madrid'},
    {name:'Nicolás González',pos:'FWD',club:'Atlético Madrid'},
    {name:'Lautaro Martínez',pos:'FWD',club:'Inter Mailand'},
    {name:'Thiago Almada',pos:'FWD',club:'Atlético Madrid'}
  ],
  'Österreich': [
    {name:'Alexander Schlager',pos:'GK',club:'Red Bull Salzburg'},
    {name:'Patrick Pentz',pos:'GK',club:'Brøndby'},
    {name:'Florian Wiegele',pos:'GK',club:'Viktoria Plzeň'},
    {name:'David Alaba',pos:'DEF',club:'Real Madrid'},
    {name:'Kevin Danso',pos:'DEF',club:'Tottenham'},
    {name:'Stefan Posch',pos:'DEF',club:'Mainz 05'},
    {name:'Philipp Lienhart',pos:'DEF',club:'SC Freiburg'},
    {name:'Phillipp Mwene',pos:'DEF',club:'Mainz 05'},
    {name:'David Affengruber',pos:'DEF',club:'Elche'},
    {name:'Marco Friedl',pos:'DEF',club:'Werder Bremen'},
    {name:'Alexander Prass',pos:'DEF',club:'TSG Hoffenheim'},
    {name:'Marcel Sabitzer',pos:'MID',club:'Borussia Dortmund'},
    {name:'Xaver Schlager',pos:'MID',club:'RB Leipzig'},
    {name:'Nicolas Seiwald',pos:'MID',club:'RB Leipzig'},
    {name:'Florian Grillitsch',pos:'MID',club:'Braga'},
    {name:'Christoph Baumgartner',pos:'MID',club:'RB Leipzig'},
    {name:'Konrad Laimer',pos:'MID',club:'Bayern München'},
    {name:'Romano Schmid',pos:'MID',club:'Werder Bremen'},
    {name:'Patrick Wimmer',pos:'MID',club:'VfL Wolfsburg'},
    {name:'Marko Arnautović',pos:'FWD',club:'Roter Stern Belgrad'},
    {name:'Michael Gregoritsch',pos:'FWD',club:'FC Augsburg'},
    {name:'Saša Kalajdžić',pos:'FWD',club:'LASK'}
  ],
  'Jordanien': [
    {name:'Yazeed Abulaila',pos:'GK',club:'Al-Hussein'},
    {name:'Abdallah Al-Fakhouri',pos:'GK',club:'Al-Wehdat'},
    {name:'Ihsan Haddad',pos:'DEF',club:'Al-Hussein'},
    {name:'Yazan Al-Arab',pos:'DEF',club:'FC Seoul'},
    {name:'Abdallah Nasib',pos:'DEF',club:'Al-Zawraa'},
    {name:'Saed Al-Rosan',pos:'DEF',club:'Al-Hussein'},
    {name:'Husam Abu Dahab',pos:'DEF',club:'Al-Faisaly'},
    {name:'Salim Obaid',pos:'DEF',club:'Al-Hussein'},
    {name:'Rajaei Ayed',pos:'MID',club:'Al-Hussein'},
    {name:'Noor Al-Rawabdeh',pos:'MID',club:'Selangor'},
    {name:'Ibrahim Sadeh',pos:'MID',club:'Al-Karma'},
    {name:'Mohammad Abu Hashish',pos:'MID',club:'Al-Karma'},
    {name:'Nizar Al-Rashdan',pos:'MID',club:'Qatar SC'},
    {name:'Musa Al-Taamari',pos:'MID',club:'Montpellier'},
    {name:'Ahmad Al-Ali',pos:'FWD',club:'Al-Jaish'},
    {name:'Baha\' Faisal',pos:'FWD',club:'Al-Wehdat'},
    {name:'Moussa Al-Taamari',pos:'FWD',club:'Montpellier'}
  ],
  'Kolumbien': [
    {name:'David Ospina',pos:'GK',club:'Atlético Nacional'},
    {name:'Camilo Vargas',pos:'GK',club:'Atlas'},
    {name:'Álvaro Montero',pos:'GK',club:'Vélez Sarsfield'},
    {name:'Davinson Sánchez',pos:'DEF',club:'Galatasaray'},
    {name:'Santiago Arias',pos:'DEF',club:'Independiente'},
    {name:'Yerry Mina',pos:'DEF',club:'Cagliari'},
    {name:'Daniel Muñoz',pos:'DEF',club:'Crystal Palace'},
    {name:'Johan Mojica',pos:'DEF',club:'Mallorca'},
    {name:'Jhon Lucumí',pos:'DEF',club:'Bologna'},
    {name:'James Rodríguez',pos:'MID',club:'Minnesota United'},
    {name:'Jefferson Lerma',pos:'MID',club:'Crystal Palace'},
    {name:'Richard Ríos',pos:'MID',club:'Palmeiras'},
    {name:'Jhon Jáder Durán',pos:'FWD',club:'Al-Qadsiah'},
    {name:'Luis Díaz',pos:'FWD',club:'Bayern München'},
    {name:'Jhon Córdoba',pos:'FWD',club:'Krasnodar'},
    {name:'Rafael Santos Borré',pos:'FWD',club:'Internacional'},
    {name:'Luis Suárez',pos:'FWD',club:'Sporting CP'},
    {name:'Cucho Hernández',pos:'FWD',club:'Real Betis'}
  ],
  'DR Kongo': [
    {name:'Lionel Mpasi',pos:'GK',club:'Le Havre'},
    {name:'Timothy Fayulu',pos:'GK',club:'Noah'},
    {name:'Dylan Batubinsika',pos:'DEF',club:'AEL'},
    {name:'Axel Tuanzebe',pos:'DEF',club:'Burnley'},
    {name:'Aaron Wan-Bissaka',pos:'DEF',club:'West Ham Utd'},
    {name:'Steve Kapuadi',pos:'DEF',club:'Widzew Łódź'},
    {name:'Samuel Moutoussamy',pos:'MID',club:'Atromitos'},
    {name:'Edo Kayembe',pos:'MID',club:'Watford'},
    {name:'Charles Pickel',pos:'MID',club:'Espanyol'},
    {name:'Gaël Kakuta',pos:'MID',club:'AEL'},
    {name:'Noah Sadiki',pos:'MID',club:'Sunderland'},
    {name:'Aaron Tshibola',pos:'MID',club:'Kilmarnock'},
    {name:'Fiston Mayele',pos:'FWD',club:'Pyramids'},
    {name:'Yoane Wissa',pos:'FWD',club:'Newcastle Utd'},
    {name:'Nathanaël Mbuku',pos:'FWD',club:'Montpellier'},
    {name:'Simon Banza',pos:'FWD',club:'Al Jazira'},
    {name:'Cédric Bakambu',pos:'FWD',club:'Marseille'},
    {name:'Théo Bongonda',pos:'FWD',club:'RC Genk'}
  ],
  'Portugal': [
    {name:'Diogo Costa',pos:'GK',club:'Porto'},
    {name:'José Sá',pos:'GK',club:'Wolverhampton'},
    {name:'Rui Silva',pos:'GK',club:'Sporting CP'},
    {name:'Rúben Dias',pos:'DEF',club:'Manchester City'},
    {name:'João Cancelo',pos:'DEF',club:'Barcelona'},
    {name:'Nélson Semedo',pos:'DEF',club:'Fenerbahçe'},
    {name:'Nuno Mendes',pos:'DEF',club:'Paris Saint-Germain'},
    {name:'Diogo Dalot',pos:'DEF',club:'Manchester Utd'},
    {name:'António Silva',pos:'DEF',club:'Benfica'},
    {name:'Bruno Fernandes',pos:'MID',club:'Manchester Utd'},
    {name:'Rúben Neves',pos:'MID',club:'Al-Hilal'},
    {name:'Vitinha',pos:'MID',club:'Paris Saint-Germain'},
    {name:'João Neves',pos:'MID',club:'Paris Saint-Germain'},
    {name:'Bernardo Silva',pos:'MID',club:'Manchester City'},
    {name:'Cristiano Ronaldo',pos:'FWD',club:'Al-Nassr'},
    {name:'João Félix',pos:'FWD',club:'Al-Nassr'},
    {name:'Rafael Leão',pos:'FWD',club:'Milan'},
    {name:'Gonçalo Guedes',pos:'FWD',club:'Real Sociedad'},
    {name:'Gonçalo Ramos',pos:'FWD',club:'Paris Saint-Germain'},
    {name:'Pedro Neto',pos:'FWD',club:'Chelsea'}
  ],
  'Usbekistan': [
    {name:'Utkir Yusupov',pos:'GK',club:'Navbahor'},
    {name:'Abduvohid Nematov',pos:'GK',club:'Nasaf'},
    {name:'Rustam Ashurmatov',pos:'DEF',club:'Esteghlal'},
    {name:'Farrukh Sayfiev',pos:'DEF',club:'Neftchi'},
    {name:'Khojiakbar Alijonov',pos:'DEF',club:'Pakhtakor'},
    {name:'Sherzod Nasrullaev',pos:'DEF',club:'Nasaf'},
    {name:'Abdukodir Khusanov',pos:'DEF',club:'Manchester City'},
    {name:'Eldor Shomurodov',pos:'FWD',club:'Roma'},
    {name:'Jaloliddin Masharipov',pos:'MID',club:'CSKA Moskau'},
    {name:'Otabek Shukurov',pos:'MID',club:'Pakhtakor'},
    {name:'Husan Kholmatov',pos:'MID',club:'Nasaf'},
    {name:'Dostonbek Khamdamov',pos:'MID',club:'Pakhtakor'},
    {name:'Akmal Mozgovoy',pos:'MID',club:'Pakhtakor'},
    {name:'Azizjon Ganiev',pos:'MID',club:'Al Bataeh'},
    {name:'Jamshid Iskanderov',pos:'FWD',club:'Pakhtakor'},
    {name:'Ulugbek Asrorov',pos:'FWD',club:'Sporting CP'},
    {name:'Bekhruz Yakhshiboev',pos:'FWD',club:'Pakhtakor'},
    {name:'Muhammadkodir Hamrobekov',pos:'FWD',club:'Pakhtakor'}
  ],
  'Kroatien': [
    {name:'Dominik Livaković',pos:'GK',club:'Dinamo Zagreb'},
    {name:'Dominik Kotarski',pos:'GK',club:'FC Kopenhagen'},
    {name:'Ivor Pandur',pos:'GK',club:'Hull City'},
    {name:'Joško Gvardiol',pos:'DEF',club:'Manchester City'},
    {name:'Duje Ćaleta-Car',pos:'DEF',club:'Real Sociedad'},
    {name:'Josip Šutalo',pos:'DEF',club:'Ajax'},
    {name:'Josip Stanišić',pos:'DEF',club:'Bayern München'},
    {name:'Marin Pongračić',pos:'DEF',club:'Fiorentina'},
    {name:'Martin Erlić',pos:'DEF',club:'Midtjylland'},
    {name:'Luka Vušković',pos:'DEF',club:'Hamburger SV'},
    {name:'Luka Modrić',pos:'MID',club:'Milan'},
    {name:'Mateo Kovačić',pos:'MID',club:'Manchester City'},
    {name:'Mario Pašalić',pos:'MID',club:'Atalanta'},
    {name:'Nikola Vlašić',pos:'MID',club:'Torino'},
    {name:'Luka Sučić',pos:'MID',club:'Real Sociedad'},
    {name:'Martin Baturina',pos:'MID',club:'Como'},
    {name:'Kristijan Jakić',pos:'MID',club:'FC Augsburg'},
    {name:'Nikola Moro',pos:'MID',club:'Bologna'},
    {name:'Ivan Perišić',pos:'FWD',club:'PSV Eindhoven'},
    {name:'Andrej Kramarić',pos:'FWD',club:'TSG Hoffenheim'},
    {name:'Ante Budimir',pos:'FWD',club:'Osasuna'},
    {name:'Bruno Petković',pos:'FWD',club:'Dinamo Zagreb'}
  ],
  'England': [
    {name:'Jordan Pickford',pos:'GK',club:'Everton'},
    {name:'Dean Henderson',pos:'GK',club:'Crystal Palace'},
    {name:'James Trafford',pos:'GK',club:'Manchester City'},
    {name:'John Stones',pos:'DEF',club:'Manchester City'},
    {name:'Marc Guéhi',pos:'DEF',club:'Manchester City'},
    {name:'Reece James',pos:'DEF',club:'Chelsea'},
    {name:'Ezri Konsa',pos:'DEF',club:'Aston Villa'},
    {name:'Dan Burn',pos:'DEF',club:'Newcastle Utd'},
    {name:'Tino Livramento',pos:'DEF',club:'Newcastle Utd'},
    {name:'Djed Spence',pos:'DEF',club:'Tottenham'},
    {name:'Jordan Henderson',pos:'MID',club:'Brentford'},
    {name:'Declan Rice',pos:'MID',club:'Arsenal'},
    {name:'Jude Bellingham',pos:'MID',club:'Real Madrid'},
    {name:'Morgan Rogers',pos:'MID',club:'Aston Villa'},
    {name:'Kobbie Mainoo',pos:'MID',club:'Manchester Utd'},
    {name:'Elliot Anderson',pos:'MID',club:'Nottingham Forest'},
    {name:'Harry Kane',pos:'FWD',club:'Bayern München'},
    {name:'Marcus Rashford',pos:'FWD',club:'Barcelona'},
    {name:'Bukayo Saka',pos:'FWD',club:'Arsenal'},
    {name:'Ollie Watkins',pos:'FWD',club:'Aston Villa'},
    {name:'Anthony Gordon',pos:'FWD',club:'Newcastle Utd'},
    {name:'Eberechi Eze',pos:'FWD',club:'Arsenal'},
    {name:'Noni Madueke',pos:'FWD',club:'Arsenal'},
    {name:'Ivan Toney',pos:'FWD',club:'Al-Ahli'}
  ],
  'Panama': [
    {name:'Luis Mejía',pos:'GK',club:'Nacional'},
    {name:'Orlando Mosquera',pos:'GK',club:'Al-Fayha'},
    {name:'Eric Davis',pos:'DEF',club:'Plaza Amador'},
    {name:'Fidel Escobar',pos:'DEF',club:'Saprissa'},
    {name:'Michael Amir Murillo',pos:'DEF',club:'Beşiktaş'},
    {name:'Roderick Miller',pos:'DEF',club:'Turan Tovuz'},
    {name:'Andrés Andrade',pos:'DEF',club:'LASK'},
    {name:'Adalberto Carrasquilla',pos:'MID',club:'FC Cincinnati'},
    {name:'Alberto Quintero',pos:'MID',club:'Tauro FC'},
    {name:'Cristian Martínez',pos:'MID',club:'Ironi Kiryat Shmona'},
    {name:'César Yanis',pos:'MID',club:'Cobresal'},
    {name:'Azarias Londoño',pos:'MID',club:'Universidad Católica'},
    {name:'José Fajardo',pos:'FWD',club:'Universidad Católica'},
    {name:'Cecilio Waterman',pos:'FWD',club:'Nacional'},
    {name:'Ismael Díaz',pos:'FWD',club:'OH Leuven'},
    {name:'Rolando Blackburn',pos:'FWD',club:'Charlotte FC'},
    {name:'Édgar Yoel Bárcenas',pos:'FWD',club:'Pachuca'},
    {name:'Carlos Harvey',pos:'MID',club:'Minnesota United'}
  ]
};

